### ISSUE TITLE
APK feature request!

### ISSUE THREAD

**Issue by gtxaspec** [hvdwolf/Joying-Recovery-Installer#1]
after APK installs recovery partition image,

have apk detect installation media:

/mnt/usb_storage
/mnt/external_sd
/mnt/external_sdio

and then appropriately create the following file:

/cache/recovery/command

with contents:

--update_package=/<install_media_path>/5009_60.zip

so on next reboot, unit will automatically boot to recovery.

**Comment by hvdwolf** [comment]
I didn't know that option. I will build it in.

**Comment by hvdwolf** [comment]
On second thought: If an sd-card or USB-stick with an update is connected, the Joying normal ROM will automatically install with a 20 seconds (or so) cancel period. That makes it actually impractical to do so. Even with a new recovery, the Joying Android layer will detect the new update.

Does the Custom ROM act differently? Does it only do "something" if you boot to recovery? Or when you create that file?

**Comment by gtxaspec** [comment]
the STOCK recovery detects the file, and begins to boot from the 5009_60 file ( which is based on dave's modified version ).  

The joying normal rom detects the update, because the APK RKUpdateService.apk is present in the stock rom, which is removed in our custom rom.

Maybe the utility should kill the RKUpdateService.apk...?

**Comment by gtxaspec** [comment]
ok, for example ( this does work i tried it )

1.  your tool installs the recovery.
2. the user is installing via USB FLASH DRIVE (which you can have a script detect,  in this case, /mnt/usb_storage would be the mount point)
3.the user selects REBOOT TO INSTALLATION (or something like that
4. the tool runs rm -rf /cache/* (to delete any old files
5. the tool creates /cache/recovery
6. the tool downloads the 5009_60.zip to /cache/5009_60.zip
7. the tool creates the file /cache/recovery/command with contents --update_package=/cache/5009_60.zip
8. the tool issues adb reboot recovery
9. the unit reboots to TWRP, and if /openrecoveryscript is present on the installation media, it begins install, otherwise, just hang out at the TWRP main screen.
10.  TWRP is now available by running the tool and selecting REBOOT TO TWRP, since it is now located on /cache (probably best to copy it there each time cause cache can be wiped )which will run step 4 to 8 again, but without the auto installation stuff due to installation files not present on usb.
11. user can now to backup or restores or whatever
12. profit

it may not be actual TWRP in the recovery partition, but good enough !

**Comment by hvdwolf** [comment]
I see what you mean.

With "5. the tool downloads the 5009_60.zip to /cache/5009_60.zip", I assume you mean "copies" from usb to /cache.

Anyway, it might take a little longer as I don't have my unit, and the seSuperUser requires different very simple system calls.

**Comment by hvdwolf** [comment]
To explain this se SuperUser behavior versus SuperSU, which we used until the custom rom.
With SuperSU I just start a command with "su -c etcera" and it will work.

With seSuperuser I have to check every command if it's working and I still don't understand why one command, almost identical to another, doesn't work, or needs single quotes or need double quotes.
We are currently using lbdroids Superuser version, but that one is 47 changes behind the official one which has quite a few bugs removed ~~, including in parameter parsing.~~

~~When I have my unit back I will first try with the official Superuser of [phhusson](https://github.com/phhusson/Superuser), also because lbdroids version is not up to date with more modern selinux policies. I don't know whether that is important for Android 6, but my major problem is inconsequent "su -c" handling.~~
That doesn't make a difference. I will simply need to check.
